// <auto-generated />
namespace MoviesApp2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adduseridtoreview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduseridtoreview));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181631367_add-user-id-to-review"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
