// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AddingNewCategory - Use 'AddingNewCategoryParams' to pass parameters into this method.
        /// </summary>
        public void AddingNewCategory()
        {
            #region Variable Declarations
            WinPane uIListakategoriimojaapPane = this.UIListakategoriimojaapWindow.UIListakategoriimojaapPane;
            WinPane uIHomePagemojaaplikacjPane = this.UIListakategoriimojaapWindow.UIHomePagemojaaplikacjPane;
            WinPane uICreatemojaaplikacjapPane = this.UIListakategoriimojaapWindow.UICreatemojaaplikacjapPane;
            WinControl uICreatemojaaplikacjapDocument = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow.UICreatemojaaplikacjapDocument;
            #endregion

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(416, 225));

            // Launch '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\15.0_5bd3f5c7\ScriptedPlugins" "Software\Microsoft\VisualStudio\15.0_5bd3f5c7_Config\ScriptedPlugins" 1098e 2f24 "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
            ApplicationUnderTest scriptedSandbox64Application = ApplicationUnderTest.Launch(this.AddingNewCategoryParams.ExePath, this.AddingNewCategoryParams.AlternateExePath, "\"Software\\Microsoft\\VisualStudio\\15.0_5bd3f5c7\\ScriptedPlugins\" \"Software\\Microso" +
                    "ft\\VisualStudio\\15.0_5bd3f5c7_Config\\ScriptedPlugins\" 1098e 2f24 \"C:/Program Fil" +
                    "es (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/p" +
                    "lugin.vs.js\"");

            // Click 'Home Page — moja aplikacja platformy ASP.NET - Goo...' pane
            Mouse.Click(uIHomePagemojaaplikacjPane, new Point(816, 128));

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(439, 225));

            // Click 'Create — moja aplikacja platformy ASP.NET - Google...' pane
            Mouse.Click(uICreatemojaaplikacjapPane, new Point(670, 280));

            // Type 'Kategoria 8' in 'Create — moja aplikacja platformy ASP.NET - Google...' document
            Keyboard.SendKeys(uICreatemojaaplikacjapDocument, this.AddingNewCategoryParams.UICreatemojaaplikacjapDocumentSendKeys, ModifierKeys.None);

            // Click 'Create — moja aplikacja platformy ASP.NET - Google...' pane
            Mouse.Click(uICreatemojaaplikacjapPane, new Point(633, 343));
        }
        
        /// <summary>
        /// AddingNewCategory2 - Use 'AddingNewCategory2Params' to pass parameters into this method.
        /// </summary>
        public void AddingNewCategory2()
        {
            #region Variable Declarations
            WinPane uIListakategoriimojaapPane = this.UIListakategoriimojaapWindow.UIListakategoriimojaapPane;
            WinPane uIHomePagemojaaplikacjPane = this.UIListakategoriimojaapWindow.UIHomePagemojaaplikacjPane;
            WinPane uICreatemojaaplikacjapPane = this.UIListakategoriimojaapWindow.UICreatemojaaplikacjapPane;
            WinControl uICreatemojaaplikacjapDocument = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow.UICreatemojaaplikacjapDocument;
            WinControl uIChromeLegacyWindowDocument = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowDocument;
            WinMenu uIAutouzupełnianieMenu = this.UIItemWindow.UIItemClient.UIAutouzupełnianieMenu;
            WinMenuItem uINowaKategoriaMenuItem = this.UIItemWindow.UIItemClient.UINowaKategoriaMenuItem;
            WinControl uICreatemojaaplikacjapDocument1 = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow2.UICreatemojaaplikacjapDocument;
            WinControl uICreatemojaaplikacjapDocument2 = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow3.UICreatemojaaplikacjapDocument;
            WinControl uIChromeLegacyWindowDocument1 = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow4.UIChromeLegacyWindowDocument;
            WinControl uIChromeLegacyWindowDocument2 = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow5.UIChromeLegacyWindowDocument;
            WinControl uIChromeLegacyWindowDocument3 = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow6.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(416, 225));

            // Launch '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\15.0_5bd3f5c7\ScriptedPlugins" "Software\Microsoft\VisualStudio\15.0_5bd3f5c7_Config\ScriptedPlugins" 1098e 2f24 "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
            ApplicationUnderTest scriptedSandbox64Application = ApplicationUnderTest.Launch(this.AddingNewCategory2Params.ExePath, this.AddingNewCategory2Params.AlternateExePath, "\"Software\\Microsoft\\VisualStudio\\15.0_5bd3f5c7\\ScriptedPlugins\" \"Software\\Microso" +
                    "ft\\VisualStudio\\15.0_5bd3f5c7_Config\\ScriptedPlugins\" 1098e 2f24 \"C:/Program Fil" +
                    "es (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/p" +
                    "lugin.vs.js\"");

            // Click 'Home Page — moja aplikacja platformy ASP.NET - Goo...' pane
            Mouse.Click(uIHomePagemojaaplikacjPane, new Point(816, 128));

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(439, 225));

            // Click 'Create — moja aplikacja platformy ASP.NET - Google...' pane
            Mouse.Click(uICreatemojaaplikacjapPane, new Point(670, 280));

            // Type 'Kategoria 8' in 'Create — moja aplikacja platformy ASP.NET - Google...' document
            Keyboard.SendKeys(uICreatemojaaplikacjapDocument, this.AddingNewCategory2Params.UICreatemojaaplikacjapDocumentSendKeys, ModifierKeys.None);

            // Click 'Create — moja aplikacja platformy ASP.NET - Google...' pane
            Mouse.Click(uICreatemojaaplikacjapPane, new Point(633, 343));

            // Click 'Home Page — moja aplikacja platformy ASP.NET - Goo...' pane
            Mouse.Click(uIHomePagemojaaplikacjPane, new Point(799, 126));

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(430, 221));

            // Click 'Create — moja aplikacja platformy ASP.NET - Google...' pane
            Mouse.Click(uICreatemojaaplikacjapPane, new Point(652, 296));

            // Type 'n' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.AddingNewCategory2Params.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Type 'owa{Space}{Down}' in 'Autouzupełnianie' popup menu
            Keyboard.SendKeys(uIAutouzupełnianieMenu, this.AddingNewCategory2Params.UIAutouzupełnianieMenuSendKeys, ModifierKeys.None);

            // Type '{Space}' in 'Nowa Kategoria' menu item
            Keyboard.SendKeys(uINowaKategoriaMenuItem, this.AddingNewCategory2Params.UINowaKategoriaMenuItemSendKeys, ModifierKeys.None);

            // Type '{Back}' in 'Create — moja aplikacja platformy ASP.NET - Google...' document
            Keyboard.SendKeys(uICreatemojaaplikacjapDocument1, this.AddingNewCategory2Params.UICreatemojaaplikacjapDocumentSendKeys1, ModifierKeys.None);

            // Type 'kategoria{Space}2' in 'Autouzupełnianie' popup menu
            Keyboard.SendKeys(uIAutouzupełnianieMenu, this.AddingNewCategory2Params.UIAutouzupełnianieMenuSendKeys1, ModifierKeys.None);

            // Click 'Create — moja aplikacja platformy ASP.NET - Google...' pane
            Mouse.Click(uICreatemojaaplikacjapPane, new Point(621, 346));

            // Move 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.StartDragging(uIListakategoriimojaapPane, new Point(441, 348));
            Mouse.StopDragging(uIListakategoriimojaapPane, 54, -4);

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(495, 344));

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(474, 344));

            // Type 'Control, Shift + i' in 'Create — moja aplikacja platformy ASP.NET - Google...' document
            Keyboard.SendKeys(uICreatemojaaplikacjapDocument2, this.AddingNewCategory2Params.UICreatemojaaplikacjapDocumentSendKeys2, (ModifierKeys.Control | ModifierKeys.Shift));

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(1896, 109));

            // Type 'Control, Shift + l' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument1, this.AddingNewCategory2Params.UIChromeLegacyWindowDocumentSendKeys1, (ModifierKeys.Control | ModifierKeys.Shift));

            // Type 'Control, Shift + l' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument2, this.AddingNewCategory2Params.UIChromeLegacyWindowDocumentSendKeys2, (ModifierKeys.Control | ModifierKeys.Shift));

            // Type 'Control, Shift + i' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument3, this.AddingNewCategory2Params.UIChromeLegacyWindowDocumentSendKeys3, (ModifierKeys.Control | ModifierKeys.Shift));

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(1906, 115));
        }
        
        /// <summary>
        /// AddingNewCategory3 - Use 'AddingNewCategory3Params' to pass parameters into this method.
        /// </summary>
        public void AddingNewCategory3()
        {
            #region Variable Declarations
            WinPane uIHomePagemojaaplikacjPane = this.UIListakategoriimojaapWindow.UIHomePagemojaaplikacjPane;
            WinPane uIListakategoriimojaapPane = this.UIListakategoriimojaapWindow.UIListakategoriimojaapPane;
            WinPane uICreatemojaaplikacjapPane = this.UIListakategoriimojaapWindow.UICreatemojaaplikacjapPane;
            WinControl uIChromeLegacyWindowDocument = this.UIListakategoriimojaapWindow.UIChromeLegacyWindowWindow7.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Home Page — moja aplikacja platformy ASP.NET - Goo...' pane
            Mouse.Click(uIHomePagemojaaplikacjPane, new Point(779, 110));

            // Click 'Lista kategorii — moja aplikacja platformy ASP.NET...' pane
            Mouse.Click(uIListakategoriimojaapPane, new Point(416, 223));

            // Click 'Create — moja aplikacja platformy ASP.NET - Google...' pane
            Mouse.Click(uICreatemojaaplikacjapPane, new Point(636, 281));

            // Type 'utworzona kategoria' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.AddingNewCategory3Params.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Create — moja aplikacja platformy ASP.NET - Google...' pane
            Mouse.Click(uICreatemojaaplikacjapPane, new Point(632, 333));
        }
        
        #region Properties
        public virtual AddingNewCategoryParams AddingNewCategoryParams
        {
            get
            {
                if ((this.mAddingNewCategoryParams == null))
                {
                    this.mAddingNewCategoryParams = new AddingNewCategoryParams();
                }
                return this.mAddingNewCategoryParams;
            }
        }
        
        public virtual AddingNewCategory2Params AddingNewCategory2Params
        {
            get
            {
                if ((this.mAddingNewCategory2Params == null))
                {
                    this.mAddingNewCategory2Params = new AddingNewCategory2Params();
                }
                return this.mAddingNewCategory2Params;
            }
        }
        
        public virtual AddingNewCategory3Params AddingNewCategory3Params
        {
            get
            {
                if ((this.mAddingNewCategory3Params == null))
                {
                    this.mAddingNewCategory3Params = new AddingNewCategory3Params();
                }
                return this.mAddingNewCategory3Params;
            }
        }
        
        public UIListakategoriimojaapWindow UIListakategoriimojaapWindow
        {
            get
            {
                if ((this.mUIListakategoriimojaapWindow == null))
                {
                    this.mUIListakategoriimojaapWindow = new UIListakategoriimojaapWindow();
                }
                return this.mUIListakategoriimojaapWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private AddingNewCategoryParams mAddingNewCategoryParams;
        
        private AddingNewCategory2Params mAddingNewCategory2Params;
        
        private AddingNewCategory3Params mAddingNewCategory3Params;
        
        private UIListakategoriimojaapWindow mUIListakategoriimojaapWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddingNewCategory'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AddingNewCategoryParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\15.0_5bd3f5c7\ScriptedPlugins" "Software\Microsoft\VisualStudio\15.0_5bd3f5c7_Config\ScriptedPlugins" 1098e 2f24 "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
        /// </summary>
        public string ExePath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\Privat" +
            "eAssemblies\\ScriptedSandbox64.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\15.0_5bd3f5c7\ScriptedPlugins" "Software\Microsoft\VisualStudio\15.0_5bd3f5c7_Config\ScriptedPlugins" 1098e 2f24 "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
        /// </summary>
        public string AlternateExePath = "%ProgramFiles(x86)%\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\PrivateAs" +
            "semblies\\ScriptedSandbox64.exe";
        
        /// <summary>
        /// Type 'Kategoria 8' in 'Create — moja aplikacja platformy ASP.NET - Google...' document
        /// </summary>
        public string UICreatemojaaplikacjapDocumentSendKeys = "Kategoria 8";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddingNewCategory2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AddingNewCategory2Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\15.0_5bd3f5c7\ScriptedPlugins" "Software\Microsoft\VisualStudio\15.0_5bd3f5c7_Config\ScriptedPlugins" 1098e 2f24 "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
        /// </summary>
        public string ExePath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\Privat" +
            "eAssemblies\\ScriptedSandbox64.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\15.0_5bd3f5c7\ScriptedPlugins" "Software\Microsoft\VisualStudio\15.0_5bd3f5c7_Config\ScriptedPlugins" 1098e 2f24 "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
        /// </summary>
        public string AlternateExePath = "%ProgramFiles(x86)%\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\PrivateAs" +
            "semblies\\ScriptedSandbox64.exe";
        
        /// <summary>
        /// Type 'Kategoria 8' in 'Create — moja aplikacja platformy ASP.NET - Google...' document
        /// </summary>
        public string UICreatemojaaplikacjapDocumentSendKeys = "Kategoria 8";
        
        /// <summary>
        /// Type 'n' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "n";
        
        /// <summary>
        /// Type 'owa{Space}{Down}' in 'Autouzupełnianie' popup menu
        /// </summary>
        public string UIAutouzupełnianieMenuSendKeys = "owa{Space}{Down}";
        
        /// <summary>
        /// Type '{Space}' in 'Nowa Kategoria' menu item
        /// </summary>
        public string UINowaKategoriaMenuItemSendKeys = "{Space}";
        
        /// <summary>
        /// Type '{Back}' in 'Create — moja aplikacja platformy ASP.NET - Google...' document
        /// </summary>
        public string UICreatemojaaplikacjapDocumentSendKeys1 = "{Back}";
        
        /// <summary>
        /// Type 'kategoria{Space}2' in 'Autouzupełnianie' popup menu
        /// </summary>
        public string UIAutouzupełnianieMenuSendKeys1 = "kategoria{Space}2";
        
        /// <summary>
        /// Type 'Control, Shift + i' in 'Create — moja aplikacja platformy ASP.NET - Google...' document
        /// </summary>
        public string UICreatemojaaplikacjapDocumentSendKeys2 = "i";
        
        /// <summary>
        /// Type 'Control, Shift + l' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "l";
        
        /// <summary>
        /// Type 'Control, Shift + l' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "l";
        
        /// <summary>
        /// Type 'Control, Shift + i' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys3 = "i";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddingNewCategory3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AddingNewCategory3Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'utworzona kategoria' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "utworzona kategoria";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIListakategoriimojaapWindow : WinWindow
    {
        
        public UIListakategoriimojaapWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
            this.WindowTitles.Add("Home Page — moja aplikacja platformy ASP.NET - Google Chrome");
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinPane UIListakategoriimojaapPane
        {
            get
            {
                if ((this.mUIListakategoriimojaapPane == null))
                {
                    this.mUIListakategoriimojaapPane = new WinPane(this);
                    #region Search Criteria
                    this.mUIListakategoriimojaapPane.SearchProperties[WinControl.PropertyNames.Name] = "Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome";
                    this.mUIListakategoriimojaapPane.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUIListakategoriimojaapPane;
            }
        }
        
        public WinPane UIHomePagemojaaplikacjPane
        {
            get
            {
                if ((this.mUIHomePagemojaaplikacjPane == null))
                {
                    this.mUIHomePagemojaaplikacjPane = new WinPane(this);
                    #region Search Criteria
                    this.mUIHomePagemojaaplikacjPane.SearchProperties[WinControl.PropertyNames.Name] = "Home Page — moja aplikacja platformy ASP.NET - Google Chrome";
                    this.mUIHomePagemojaaplikacjPane.WindowTitles.Add("Home Page — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUIHomePagemojaaplikacjPane;
            }
        }
        
        public WinPane UICreatemojaaplikacjapPane
        {
            get
            {
                if ((this.mUICreatemojaaplikacjapPane == null))
                {
                    this.mUICreatemojaaplikacjapPane = new WinPane(this);
                    #region Search Criteria
                    this.mUICreatemojaaplikacjapPane.SearchProperties[WinControl.PropertyNames.Name] = "Create — moja aplikacja platformy ASP.NET - Google Chrome";
                    this.mUICreatemojaaplikacjapPane.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUICreatemojaaplikacjapPane;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow1 == null))
                {
                    this.mUIChromeLegacyWindowWindow1 = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow2 UIChromeLegacyWindowWindow2
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow2 == null))
                {
                    this.mUIChromeLegacyWindowWindow2 = new UIChromeLegacyWindowWindow2(this);
                }
                return this.mUIChromeLegacyWindowWindow2;
            }
        }
        
        public UIChromeLegacyWindowWindow3 UIChromeLegacyWindowWindow3
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow3 == null))
                {
                    this.mUIChromeLegacyWindowWindow3 = new UIChromeLegacyWindowWindow3(this);
                }
                return this.mUIChromeLegacyWindowWindow3;
            }
        }
        
        public UIChromeLegacyWindowWindow4 UIChromeLegacyWindowWindow4
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow4 == null))
                {
                    this.mUIChromeLegacyWindowWindow4 = new UIChromeLegacyWindowWindow4(this);
                }
                return this.mUIChromeLegacyWindowWindow4;
            }
        }
        
        public UIChromeLegacyWindowWindow5 UIChromeLegacyWindowWindow5
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow5 == null))
                {
                    this.mUIChromeLegacyWindowWindow5 = new UIChromeLegacyWindowWindow5(this);
                }
                return this.mUIChromeLegacyWindowWindow5;
            }
        }
        
        public UIChromeLegacyWindowWindow6 UIChromeLegacyWindowWindow6
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow6 == null))
                {
                    this.mUIChromeLegacyWindowWindow6 = new UIChromeLegacyWindowWindow6(this);
                }
                return this.mUIChromeLegacyWindowWindow6;
            }
        }
        
        public UIChromeLegacyWindowWindow7 UIChromeLegacyWindowWindow7
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow7 == null))
                {
                    this.mUIChromeLegacyWindowWindow7 = new UIChromeLegacyWindowWindow7(this);
                }
                return this.mUIChromeLegacyWindowWindow7;
            }
        }
        #endregion
        
        #region Fields
        private WinPane mUIListakategoriimojaapPane;
        
        private WinPane mUIHomePagemojaaplikacjPane;
        
        private WinPane mUICreatemojaaplikacjapPane;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow1;
        
        private UIChromeLegacyWindowWindow2 mUIChromeLegacyWindowWindow2;
        
        private UIChromeLegacyWindowWindow3 mUIChromeLegacyWindowWindow3;
        
        private UIChromeLegacyWindowWindow4 mUIChromeLegacyWindowWindow4;
        
        private UIChromeLegacyWindowWindow5 mUIChromeLegacyWindowWindow5;
        
        private UIChromeLegacyWindowWindow6 mUIChromeLegacyWindowWindow6;
        
        private UIChromeLegacyWindowWindow7 mUIChromeLegacyWindowWindow7;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1802041744";
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UICreatemojaaplikacjapDocument
        {
            get
            {
                if ((this.mUICreatemojaaplikacjapDocument == null))
                {
                    this.mUICreatemojaaplikacjapDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUICreatemojaaplikacjapDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUICreatemojaaplikacjapDocument.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUICreatemojaaplikacjapDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUICreatemojaaplikacjapDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1835534640";
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            this.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow2 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1835534640";
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            this.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UICreatemojaaplikacjapDocument
        {
            get
            {
                if ((this.mUICreatemojaaplikacjapDocument == null))
                {
                    this.mUICreatemojaaplikacjapDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUICreatemojaaplikacjapDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUICreatemojaaplikacjapDocument.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    this.mUICreatemojaaplikacjapDocument.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUICreatemojaaplikacjapDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUICreatemojaaplikacjapDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow3 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1835534640";
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            this.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UICreatemojaaplikacjapDocument
        {
            get
            {
                if ((this.mUICreatemojaaplikacjapDocument == null))
                {
                    this.mUICreatemojaaplikacjapDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUICreatemojaaplikacjapDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUICreatemojaaplikacjapDocument.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    this.mUICreatemojaaplikacjapDocument.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUICreatemojaaplikacjapDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUICreatemojaaplikacjapDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow4 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1835534640";
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            this.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow5 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1835534640";
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            this.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow6 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1835534640";
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            this.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Lista kategorii — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow7 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1846140912";
            this.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Create — moja aplikacja platformy ASP.NET - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            #endregion
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinMenu UIAutouzupełnianieMenu
        {
            get
            {
                if ((this.mUIAutouzupełnianieMenu == null))
                {
                    this.mUIAutouzupełnianieMenu = new WinMenu(this);
                    #region Search Criteria
                    this.mUIAutouzupełnianieMenu.SearchProperties[WinMenu.PropertyNames.Name] = "Autouzupełnianie";
                    #endregion
                }
                return this.mUIAutouzupełnianieMenu;
            }
        }
        
        public WinMenuItem UINowaKategoriaMenuItem
        {
            get
            {
                if ((this.mUINowaKategoriaMenuItem == null))
                {
                    this.mUINowaKategoriaMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUINowaKategoriaMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Nowa Kategoria ";
                    #endregion
                }
                return this.mUINowaKategoriaMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenu mUIAutouzupełnianieMenu;
        
        private WinMenuItem mUINowaKategoriaMenuItem;
        #endregion
    }
}
